name: Feature
about: 新功能・功能改善相关 Issue
title: "feat: "
labels: ["feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 请用中文说明本 Issue 要实现什么。
      placeholder: 例如：新增账单页面可以切换支付账户。
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: 背景 / 目的
      description: 为什么需要这个功能？解决什么问题？
    validations:
      required: false
  - type: textarea
    id: branch
    attributes:
      label: Branch 命名
      description: 创建分支时请使用 feature/#issue_number_xxx 格式。
      placeholder: feature/#302_new_bill_can_change_account
    validations:
      required: false
  - type: textarea
    id: tasks
    attributes:
      label: TODO
      description: 拆分需要完成的任务。
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: 备注
      description: 其他补充信息。
    validations:
      required: false
